Nompilo PHC Website/Models/Report.cs
namespace Nompilo_PHC_Website.Models
{
    public class Report
    {
        public int Months { get;set; }
        public int Weight { get;set; }
    }
}

Nompilo PHC Website/Controllers/WalkController.cs
using Microsoft.AspNetCore.Mvc;
using Nompilo_PHC_Website.Data;
using Nompilo_PHC_Website.Models;

namespace Nompilo_PHC_Website.Controllers
{
    public class WalkController : Controller
    {
        private readonly ApplicationDbContext dbContext;
        public WalkController(ApplicationDbContext dbC)
        {
            dbContext = dbC;
        }
        //[ValidateAntiForgeryToken]
        [HttpGet]
        
        public IActionResult Index()
        {
            IEnumerable<Booking> book = dbContext.Bookings;
            return View(book);
        } 
        public IActionResult Info()
        {
            
            return View();
        } 
      

    }
}

Nompilo PHC Website/Views/Walk/Index.cshtml
@{
    
    ViewData["Title"] = "Index";
}
@model IEnumerable<Booking>
@{

    string special = "@gmail.com", special1 = "@outlook.com", special2 = "@mandela.ac.za", special3 = "@nompilo.co.za";
    string name = User.Identity?.Name.ToString();
    if (name.ToLowerInvariant().Contains(special))
    {
        name = name.Replace(special, " ");
    }
    else if (name.ToLowerInvariant().Contains(special1))
    {
        name = name.Replace(special1, " ");
    }
    else if (name.ToLowerInvariant().Contains(special2))
    {
        name = name.Replace(special2, " ");
    }
    else if (name.ToLowerInvariant().Contains(special3))
    {
        name = name.Replace(special3, " ");
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link href="style.css" rel="stylesheet"> -->
    <title>Count Down Room</title>
    <style>
        
         * {
            margin: 0;
            padding: 0;
            outline: none;
            border: none;
            text-decoration: none;
            box-sizing: border-box;
            font-family: "Poppins", sans-serif;
            color: white;
            font-weight: 700;
        }


        body{
            min-height: 900px;
        }
        nav{
        visibility:hidden;
        
        }
        .container {
            display: flex;
        }

        .nv {
            position: absolute;
           
            visibility:visible;
            top: 0px;
            bottom: 0;
            height: auto;
            left: 0;
            background-color: #0a2a43;
            width: 270px;
            overflow: hidden;
            box-shadow: 0 20px 35px rgba(0, 0, 0, 0.1);
            color: white;
            font-weight: 700px;
        }

        .logo {
            text-align: center;
            display: flex;
            margin: 10px 0 0 10px;
        }

            .logo img {
                width: 45px;
                height: 45px;
                border-radius: 50%;
            }

            .logo span {
                font-weight: bold;
                padding-left: 15px;
                font-size: 18px;
                text-transform: uppercase;
            }

        a {
            position: relative;
            color: rgb(85, 83, 83);
            font-size: 14px;
            display: table;
            width: 280px;
            padding: 10px;
        }

        .nv .fas {
            position: relative;
            width: 70px;
            height: 40px;
            top: 14px;
            font-size: 20px;
            text-align: center;
        }

        .nav-item {
            position: relative;
            top: 12px;
            margin-left: 10px;
        }

        a:hover {
            background: #eee;
        }

        .logout {
            position: absolute;
        }
      
    </style>
</head>

<body class="contnr">
    <div class="contnr-index nav">
            <nav class = "nv">
                <ul>
                    <li>
                        <a href="#" class="logo">
                            <img src="~/css/person.jpg" alt="">
                            <span class="nav-item">Ndumiso</span>
                        </a>
                        <br />
                    </li>

                    <li>
                        <a asp-action="Index" asp-controller="Walk">
                            <i class="fas fa-home"></i>
                            <span class="nav-item">Home</span>
                        </a>
                        <br />
                    </li>


                    <li>
                        <a asp-action="Doctors" asp-controller="Dr">
                            <i class="fas fa-star"></i>
                            <span class="nav-item">Doctors</span>
                        </a>
                        <br />
                    </li>

                    <li>
                        <a asp-action="Booking" asp-controller="Booking">
                            <i class="fas fa-star"></i>
                            <span class="nav-item">Booking</span>
                        </a>
                        <br />
                    </li>

                    <li>
                       <a asp-action="Info" asp-controller="Walk">
                        <i class="fas fa-star"></i>
                        <span class="nav-item">Location</span>
                         </a>
                        <br />
                    </li>

                    <li>
                        <br />
                        <br />
                        <a asp-action="Home" asp-controller="Home" class="logout">
                            <i class="fas fa-sign-out-alt"></i>
                            <span class="nav-item">Log out</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
        
         
      <div class="contnt">
       

     
    
            <br />
            <br />
            <br />
        
            <h1><span>Appointment</span> Date and <span>Time</span> </h1>

            <div class="launch-time">

                <div>

                    <p id="Days">00</p>
                    <br />
                    <br />
                    <span>Days</span>

                </div>

                <div>

                    <p id="Hours">00</p>
                    <br />
                    <br />
                    <span>Hours</span>

                </div>

                <div>

                    <p id="Minutes">00</p>
                    <br />
                    <br />
                    <span>Minutes</span>

                </div>
          
                <div>
                    <p id="Seconds">00</p>
                    <br />
                    <br />
                    <span>Seconds</span>
                </div>

            </div>
            <br />
            <p>Please arrive 5 minutes early for your Appointment</p>

            <br/>
            
          
            
            <h1 id="frm">
           
                    <iframe  width="50" height="50" src="https://www.youtube.com/embed/UWmGYgl7GIY?si=D-lCiEVtSO75ibjf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

             </h1>
           
           
      
    </div>

   @* <span>
                <p>Music</p>
            </span>
*@
    <img src="~/css/rocket.png" class="rocket">

    @foreach(var dt in Model)
    {
        if (dt.services == "Walk in's")
        {
          <script>

               var countDownDate = new Date("@dt.datetimes").getTime();

               var x = setInterval(function()
               {
                 var now = new Date().getTime();
                 var difference = countDownDate - now;

                var Days = Math.floor(difference / (1000 * 60 * 60 *24));
                var Hours = Math.floor((difference % (1000 * 60 * 60 *24)) /(1000 * 60 * 60));
                var Minutes = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
                var Seconds = Math.floor((difference % (1000 * 60)) / 1000);


                document.getElementById("Days").innerHTML = Days
                document.getElementById("Hours").innerHTML = Hours
                document.getElementById("Minutes").innerHTML = Minutes
                document.getElementById("Seconds").innerHTML = Seconds

                if(Minutes ==2 && Seconds == 0 ){
                    alert("Please prepare come forward to the Dr of your choice")
                }

                if(difference < 0)
                {
                    document.getElementById("Days").innerHTML = "00"
                    document.getElementById("Hours").innerHTML = "00"
                    document.getElementById("Minutes").innerHTML = "00"
                    document.getElementById("Seconds").innerHTML = "00"
            
                }

               },1000);
       

          </script>
        }
    }
</body>
</html>

Nompilo PHC Website/Views/Walk/Info.cshtml
@using Microsoft.AspNetCore.Identity
@{
    Layout = null;
}
@{

    string special = "@gmail.com", special1 = "@outlook.com", special2 = "@mandela.ac.za", special3 = "@nompilo.co.za";
    string name = User.Identity?.Name.ToString();
    if (name.ToLowerInvariant().Contains(special))
    {
        name = name.Replace(special, " ");
    }
    else if (name.ToLowerInvariant().Contains(special1))
    {
        name = name.Replace(special1, " ");
    }
    else if (name.ToLowerInvariant().Contains(special2))
    {
        name = name.Replace(special2, " ");
    }
    else if (name.ToLowerInvariant().Contains(special3))
    {
        name = name.Replace(special3, " ");
    }
}
   

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8" />

    @* <link rel="stylesheet" href="~/css/dashboardstyle.css" />
   @* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">*@
    <style>
        /* import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700");*/

        * {
            margin: 0;
            padding: 0;
            outline: none;
            border: none;
            text-decoration: none;
            box-sizing: border-box;
            font-family: "Poppins", sans-serif;
            color: white;
        }


        .container {
            display: flex;
        }

        nav {
            position: absolute;
            top: 0px;
            bottom: 0;
            height:1680px;
            left: 0;
            background-color: #0a2a43;
            width: 280px;
            overflow: hidden;
            box-shadow: 0 20px 35px rgba(0, 0, 0, 0.1);
             
        }

        .logo {
            text-align: center;
            display: flex;
            margin: 10px 0 0 10px;
        }

            .logo img {
                width: 45px;
                height: 45px;
                border-radius: 50%;
            }

            .logo span {
                font-weight: bold;
                padding-left: 15px;
                font-size: 18px;
                text-transform: uppercase;
            }

        a {
            position: relative;
            color: rgb(85, 83, 83);
            font-size: 14px;
            display: table;
            width: 280px;
            padding: 10px;
        }

        nav .fas {
            position: relative;
            width: 70px;
            height: 40px;
            top: 14px;
            font-size: 20px;
            text-align: center;
        }

        .nav-item {
            position: relative;
            top: 12px;
            margin-left: 10px;
        }

        a:hover {
            background: #eee;
        }

        .logout {
            position: absolute;
        }

        .mn {
           margin-left:290px;

           position:relative;
           height:auto;
           width:auto;
        }


        /*card*/
         .card {
            position: relative;
            width: 700px;
            height: 350px;
            background: #ccc;
            border-radius: 20px;
            display: flex;
            align-items: center;
            transition: 0.5s;
        }

            .card .circle {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                overflow: hidden
            }

            .card .circle::before {
                content: '';
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background: #d83133;
                clip-path: circle(120px at center);
                transition: 0.5s;
            }

            .card:hover .circle:before {
                background: #0065c3;
                clip-path: circle(400px at center);
            }

            .card img {
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                height: 300px;
                pointer-events: none;
                transition: 0.5s;
            }

            .card:hover img {
                left: 100%;
                height: 500px;
            }

            .card .content {
                position: relative;
                width: 50%;
                left: 20%;
                padding: 20px 20px 20px 40px;
                transition: 0.5s;
                opacity: 0;
                visibility: hidden
            }

            .card:hover .content {
                left: 0;
                opacity: 1;
                visibility: visible;
            }

            .card .content h2 {
                font-size: 2em;
                color: #fff;
                line-height: 1em;
            }

            .card .content p {
                color: #fff;
            }

    </style>

     <title>Location</title>
</head>
<body>
    <div class="container">
        <nav>
            <ul>
                <li>
                    <a href="#" class="logo">
                        <img src="~/css/person.jpg" alt="">
                        <span class="nav-item">Ndumiso</span>
                    </a>
                    <br />
                </li>

                <li>
                    <a asp-action="Index" asp-controller="Walk">
                        <i class="fas fa-home"></i>
                        <span class="nav-item">Home</span>
                    </a>
                    <br />
                </li>


                <li>
                    <a asp-action="Doctors" asp-controller="Dr">
                        <i class="fas fa-star"></i>
                        <span class="nav-item">Doctors</span>
                    </a>
                    <br />
                </li>

                <li>
                    <a asp-action="Booking" asp-controller="Booking">
                        <i class="fas fa-star"></i>
                        <span class="nav-item">Booking</span>
                    </a>
                    <br />
                </li>

                <li>
                    <a asp-action="Info" asp-controller="Walk">
                        <i class="fas fa-star"></i>
                        <span class="nav-item">Location</span>
                    </a>
                    <br />
                </li>

                <li>
                    <br />
                    <br />
                    <a asp-action="Home" asp-controller="Home" class="logout">
                        <i class="fas fa-sign-out-alt"></i>
                        <span class="nav-item">Log out</span>
                    </a>
                </li>
            </ul>
        </nav>
        <section class="mn">
        <h1 style=" margin-left: 380px; font-size:30px;font-weight:700;top:auto">Did you know You can <br/>Search for our Location on Google Maps</h1>

          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3500.7928038669825!2d32.02047337495539!3d-28.66592196872839!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1efa3ddbe6e8ebeb%3A0xc4eab6b349ec541f!2sNseleni%20Old%20Clinic!5e0!3m2!1sen!2sza!4v1698388898791!5m2!1sen!2sza" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
           
        </section>

    </div>
</body>
</html>

Nompilo PHC Website/Views/Walk/Report.cshtml
@model IEnumerable<Report_Wlk>;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report</title>
    <link href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css" rel="stylesheet" />
    
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script> 
    <script src="https://cdn.datatables.net/buttons/2.3.3/js/dataTables.buttons.min.js"></script> 
    <script src="https://cdnjs.cloudfare.com/ajax/libs/jszip/3.1.3/jzip.min.js"></script>

    <script src="https://cdnjs.cloudfare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>

    <script src="https://cdnjs.cloudfare.com/ajax/libs/pdfmake/0.1.53/vfsfonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>



    <style>
      
    </style>
</head>
<body>
    
    <div class="text-center">
        <h1 class="display-4">Report to CSV, PDF, PRINT</h1>
        <div class = "cntnt">
            <table id="exmpl" class="display nowrap" style="width:100%">
                <thead>
                    <td>Name</td
                    <td>Surname</td>
                </thead>/>

                <tbody>
                    @foreach(var x in Model)
                    {
                        <tr>
                            <td> @x.Name</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <script>
$(document).ready(function() {
    $('#exmpl').DataTable({
        dom: 'lBfrtip',
        buttons: ['copy', 'csv', 'excel', 'pdf', 'print']
    });
});
    </script>

</body>
</html>