Nompilo PHC Website/Models/Calculator.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Nompilo_PHC_Website.Models
{
    public class Calculator
    {
        [Required]
        [BindProperty]
        public DateTime Conception { get; set; }
    }
}

Nompilo PHC Website/Models/Report.cs
namespace Nompilo_PHC_Website.Models
{
    public class Report
    {
        public int Months { get;set; }
        public int Weight { get;set; }
    }
}

Nompilo PHC Website/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Nompilo_PHC_Website.Controllers
{
    public class DashboardController : Controller
    {
        
        public IActionResult Patient()
        {
            return View();
        }

        public IActionResult Doctor()
        {
            return View();
        }
        public IActionResult LabScientist()
        {
            return View();
        }
        public IActionResult Nurse()
        {
            return View();
        }
        
        public IActionResult Admin()
        {
            return View();
        }
    }
}

Nompilo PHC Website/Controllers/PrenatalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Nompilo_PHC_Website.Data;
using Nompilo_PHC_Website.Models;
using System.Data;
using iText.Kernel.Pdf;
using iText.Layout.Element;
using iText.Layout.Properties;
using iText.Layout;
using iText.Kernel.Events;
using iText.Kernel.Pdf.Canvas.Draw;
using iText.Kernel.Colors;
using iText.Kernel.Font;
using iText.Kernel.Pdf.Canvas;
using iText.Layout.Borders;
using iText.IO.Font;
using iText.IO.Image;

namespace Nompilo_PHC_Website.Controllers
{
    public class PrenatalController : Controller
    {
        /*static DateOnly Calc*/
        private readonly ApplicationDbContext _Booking;
        private readonly ApplicationDbContext _Pregnancy;
        private readonly ApplicationDbContext _Patients;

        public PrenatalController(ApplicationDbContext booking)
        {
            _Booking = booking;
            _Pregnancy = booking;
            _Patients = booking;

        }
        private static List<Calculator> Calc = new List<Calculator>();
        private static List<Report> Rep = new List<Report>();
        public IActionResult Dashboard()
        {
            IEnumerable<Booking> bookings = _Booking.Bookings;
            return View(bookings);
        }
        public IActionResult Calculator()
        {
            var Cal = new Calculator();
            return View(Cal);
        }
        [HttpPost]
        public IActionResult CalculatorSub(Calculator cal)
        {
            if (ModelState.IsValid)
            {
                Calc.Add(cal);
                return RedirectToAction("Results");
            }
            return RedirectToAction("Calculator");
        }
        public IActionResult Results()
        {
            return View(Calc);
        }
        public IActionResult Support()
        {
            return View();
        }
        public IActionResult DocDash()
        {
            return View();
        }
        public IActionResult Pregnantpatients()
        {

            IEnumerable<FpregRefers> preg = _Pregnancy.FpregRefers;
            return View(preg);
        }
        public IActionResult Patients()
        {
            var patient = new PrenatalPatients();
            IEnumerable<FpregRefers> preg = _Pregnancy.FpregRefers;
            ViewBag.PatientN = new SelectList(preg, "RefName", "RefName");
            ViewBag.PatientL = new SelectList(preg, "RefLastName", "RefLastName");
            ViewBag.PatientD = new SelectList(preg, "RefDate", "RefDate");
            return View(patient);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPatients(PrenatalPatients patients)
        {
            if (ModelState.IsValid)
            {
                _Patients.PrenatalPatients.Add(patients);
                _Patients.SaveChanges();
                return RedirectToAction("DisplayP");
            }
            return RedirectToAction("Patients");
        }
        public IActionResult DisplayP()
        {
            IEnumerable<PrenatalPatients> preg = _Patients.PrenatalPatients;
            return View(preg);
        }
        public IActionResult Report()
        {
            var report = new Report();
            return View(report);
        }
        public IActionResult SearchReport(Report report)
        {

            if (ModelState.IsValid)
            {
                Rep.Clear();
                Rep.Add(report);
                return RedirectToAction("DisplayReport");
            }
            return RedirectToAction("Report");
        }
        public IActionResult DisplayReport()
        {
            IEnumerable<PrenatalPatients> preg = _Patients.PrenatalPatients;

            var combinedclass = new Combined
            {
                Patients = preg,
                Report = Rep
            };
            return View(combinedclass);
        }

        public IActionResult GenerateReport()
        {
            // Retrieve product data from the database
            var prenatal = _Booking.PrenatalPatients;

            // Generate report and save as PDF
            var filePath = "Prenatal.pdf";
            GeneratePDFReport(prenatal, filePath);

            // Return a file download response
            var fileBytes = System.IO.File.ReadAllBytes(filePath);
            return File(fileBytes, "application/pdf", "PreNatalReport.pdf");
        }
        private void GeneratePDFReport(IEnumerable<PrenatalPatients> prenatal, string filePath)
        {
            using (var writer = new PdfWriter(filePath))
            {
                using (var pdfDocument = new PdfDocument(writer))
                {
                    var document = new Document(pdfDocument);

                    // Add header
                    document.Add(new Paragraph("-----------------").SetTextAlignment(TextAlignment.CENTER).SetMarginBottom(20));
                    document.Add(new Paragraph("PreNatal Report").SetTextAlignment(TextAlignment.CENTER).SetFontSize(20).SetBold());
                    document.Add(new Paragraph("-----------------").SetTextAlignment(TextAlignment.CENTER).SetMarginBottom(20));

                    //Adding Logo


                    // Add date and time
                    var currentDate = DateTime.Now.ToString("d-MMMM-yyyy");
                    document.Add(new Paragraph($"Date: {currentDate}").SetTextAlignment(TextAlignment.RIGHT).SetMarginBottom(5));

                    // Add address section
                    var addressParagraph = new Paragraph()
                        .Add(new Text("Nompilo PHC").SetBold()).Add(new LineSeparator(new SolidLine())).Add(Environment.NewLine)
                        .Add("22 Admiralty Crescent").AddTabStops(new TabStop(500, TabAlignment.LEFT)).Add("City, State, Zip Code").Add(Environment.NewLine)
                        .Add("Phone: (041) 456-7890").AddTabStops(new TabStop(500, TabAlignment.LEFT))
                        .Add(new Tab()).Add("Email: info@datageeks.com");
                    document.Add(addressParagraph);
                    document.Add(new Paragraph().SetMarginBottom(20));

                    // Add product table
                    var table = new iText.Layout.Element.Table(UnitValue.CreatePercentArray(4)).UseAllAvailableWidth();

                    // Set table headers

                    table.AddHeaderCell(CreateHeaderCell("Name"));
                    table.AddHeaderCell(CreateHeaderCell("Last Name"));
                    table.AddHeaderCell(CreateHeaderCell("Months"));
                    table.AddHeaderCell(CreateHeaderCell("Weight"));




                    // Set table data
                    foreach (var prenatals in prenatal)
                    {

                        table.AddCell(CreateTableCell(prenatals.Name.ToString()));
                        table.AddCell(CreateTableCell(prenatals.LastName.ToString()));
                        table.AddCell(CreateTableCell(prenatals.Months.ToString()));
                        table.AddCell(CreateTableCell(prenatals.Weight.ToString()));


                    }

                    // Add table footer with total
                    table.AddFooterCell(new Cell().SetBorder(Border.NO_BORDER));
                    table.AddFooterCell(new Cell().SetBorder(Border.NO_BORDER));
                    table.AddFooterCell(new Cell().SetBorder(Border.NO_BORDER));
                    //table.AddFooterCell(CreateHeaderCell("Total:")); // Header c
                    table.AddFooterCell(new Cell().SetBorder(Border.NO_BORDER));
                    table.AddFooterCell(new Cell().SetBorder(Border.NO_BORDER));
                    table.AddFooterCell(new Cell().SetBorder(Border.NO_BORDER));
                    //table.AddFooterCell(CreateTableCell(total.ToString("C"))); 

                    document.Add(table);

                    // Add page numbering
                    var pageNumber = new PageNumberDocumentEventHandler();
                    pdfDocument.AddEventHandler(PdfDocumentEvent.END_PAGE, pageNumber);

                    document.Close();
                }
            }

            Console.WriteLine("Report generated successfully and saved to the specified PDF file.");
        }
        private Cell CreateHeaderCell(string text)
        {
            var cell = new Cell().SetTextAlignment(TextAlignment.CENTER).SetBackgroundColor(ColorConstants.LIGHT_GRAY)
                .SetPadding(5).SetFontColor(DeviceRgb.WHITE).SetFont(PdfFontFactory.CreateFont());

            cell.Add(new Paragraph(text).SetBold());

            return cell;
        }
        private Cell CreateTableCell(string text)
        {
            return new Cell().SetTextAlignment(TextAlignment.CENTER).SetPadding(5).Add(new Paragraph(text));
        }
        public class PageNumberDocumentEventHandler : IEventHandler
        {
            private int pageCount;

            public void HandleEvent(Event currentEvent)
            {
                PdfDocumentEvent docEvent = (PdfDocumentEvent)currentEvent;
                PdfDocument pdfDoc = docEvent.GetDocument();
                PdfPage page = docEvent.GetPage();

                pageCount = pdfDoc.GetNumberOfPages();
                PdfCanvas canvas = new PdfCanvas(page.NewContentStreamBefore(), page.GetResources(), pdfDoc);
                iText.Kernel.Geom.Rectangle pageSize = page.GetPageSizeWithRotation();
                canvas.BeginText()
                    .SetFontAndSize(PdfFontFactory.CreateFont(), 10)
                    .MoveText(pageSize.GetWidth() - 100, 20)
                    .ShowText($"Page {pageCount}")
                    .EndText();
                canvas.Release();
            }
        }
        public IActionResult Menu()
        {
            return View();
        }
    }
}

Nompilo PHC Website/Views/Prenatal/Calculator.cshtml
@model Calculator;
@{
    ViewData["Title"] = "Calculator";
}
<head>
    <link href='https://fonts.googleapis.com/css?family=Heebo' rel='stylesheet'>
    <style>
        h1{
            font-weight: bold;
            font-size: 4rem;
            color: Black;
            font-family: 'Times New Roman', Times, serif;
            text-align:center;
        }

        body {
            padding: 0;
            margin: 0;
        }
        button{
            border-radius:7px;
        }
        #info{
            margin: auto;
        }
    </style>
</head>
<body>
<div id="top">
        <h1> Welcome Prenatal Care</h1>
</div>
<br />
<br />
<form id="Cal" asp-controller="Prenatal" asp-action="CalculatorSub" method="post">
        <h2>Pregnancy Due Date Calculator</h2>
    <label>Date of conception: </label>
        @Html.TextBoxFor(m=>m.Conception,new{type = "date"})
        <button class="w-100 btn btn-lg btn-primary" type="submit"><i class="fas fa-calendar-week"></i>Calculate</button>
        <hr />
        <p>This is not a diagnosis. The calculations that are provided are estimates based on averages.</p>
</form>
<br />
    <div class="card w-75" id="info">
        <div class="card-body">
            <h5 class="card-title">How Soon Can I Take a Pregnancy Test?</h5>
            <p class="card-text">A missed menstruation cycle is one of the <a href="https://americanpregnancy.org/pregnancy-symptoms/early-signs-of-pregnancy/">earliest signs of pregnancy</a>. That’s why we usually recommend waiting until you’ve missed your period before taking a <a href="https://americanpregnancy.org/getting-pregnant/understanding-pregnancy-tests/">pregnancy test</a>.  If you can’t wait that long and you know the day of your last period we can calculate possible conception and your pregnancy due date.</p>
        </div>
    </div>
    <br />
    <div class="card w-75" id="info">
        <div class="card-body">
            <h5 class="card-title">Did You Get a Positive Test? Here's What to do Next.</h5>
            <p class="card-text">If you would like to speak to someone about your pregnancy, call us toll free at +27-638-472-023. You can also explore our numerous articles about how to have a <a href="https://americanpregnancy.org/healthy-pregnancy/health-nutrition/">healthy pregnancy</a>.</p>
        </div>
    </div>
    <a asp-controller="Prenatal" asp-action="Dashboard"><button class="btn-danger" id="back">Back</button></a>
</body>

Nompilo PHC Website/Views/Prenatal/DisplayP.cshtml
@model IEnumerable<PrenatalPatients>
@{
    ViewData["Title"] = "DisplayP";
    Layout = "~/Views/Shared/DoctorLayout.cshtml";
}
<body id="home">
    <h1 id="bookh1">Pregnant Patients</h1>
    <table class="table table-dark">
        @{
            if (Model.Count() > 0)
            {
                <thead class="table-primary">
                    <tr>
                        <th>Patient Name</th>
                        <th>Last Name</th>
                        <th>Reference Date</th>
                        <th>Months Pregnant</th>
                        <th>Weight</th>
                        <th>Urine Test</th>
                    </tr>
                </thead>
                @foreach (var preg in Model)
                {
                    <tr>
                        <td>@preg.Name</td>
                        <td>@preg.LastName</td>
                        <td>@preg.Date</td>
                        <td>@preg.Months</td>
                        <td>@preg.Weight</td>
                        <td>@preg.Urine</td>

                    </tr>
                }
            }
            else{
                <h2 style="text-align:center">Sorry you have no added patients</h2>
            }
        }
    </table>
    <br />
    <a asp-action="Patients" asp-controller="Prenatal"><button class="w-100 btn btn-lg btn-primary">Add patient</button></a>
    <br />
    <br />
    <br />
    <br />
    <a asp-action="DocDash" asp-controller="Prenatal"><button id="back" class="btn-danger">Back</button></a>

</body>

Nompilo PHC Website/Views/Prenatal/DisplayReport.cshtml
@model Combined
@{
    ViewData["Title"] = "Report";
    Layout = "~/Views/Shared/DoctorLayout.cshtml";
}
<body id="home">
<style>
    #btn {
        background: #2196F3;
        padding: 10px;
        font-size: 14px;
        border: 1px solid grey;
        float: left;
        width: 15%;
    }

    select {
        padding: 10px;
        font-size: 17px;
        border: 1px solid grey;
        float: left;
        width: 30%;
        background: #f1f1f1;
    }

    form #btn:hover {
        background: #0b7dda;
    }

    /* Clear floats */
    form::after {
        content: "";
        clear: both;
        display: table;
    }

    form {
        margin: auto;
        width: 100%;
    }

</style>
<h1 id="bookh1">Patients Report</h1>
<br />
@foreach (var x in Model.Report)
{
    <form asp-action="Report" asp-controller="Prenatal">
            <select asp-for="@x.Months">
                <option selected disabled value="0">All Months</option>
                <option value="1">1 Month</option>
                <option value="2">2 Months</option>
                <option value="3">3 Months</option>
                <option value="4">4 Months</option>
                <option value="5">5 Months</option>
                <option value="6">6 Months</option>
                <option value="7">7 Months</option>
                <option value="8">8 Months</option>
                <option value="9">9 Months</option>
            </select>
            <select asp-for="@x.Weight">
                <option selected disabled value="0">All Weight</option>
                <option value="1">More than 60kg</option>
                <option value="2">Less than 60kg</option>
            </select>
        <button id="btn" type="submit"><img src="~/css/search.svg" height="17" width="17" /> </button>
    </form>
    <br />
    <br />
    <table class="table table-dark">
                <thead class="table-primary">
                    <tr>
                        <th>Patient Name</th>
                        <th>Last Name</th>
                        <th>Months Pregnant</th>
                        <th>Weight</th>
                    </tr>
                </thead>
                @foreach (var preg in Model.Patients)
                {
                    if (x.Months == preg.Months && x.Weight == 0)
                    {
                    <tr>
                        <td>@preg.Name</td>
                        <td>@preg.LastName</td>
                        <td>@preg.Months</td>
                        <td>@preg.Weight</td>
                    </tr>
                    }
                    else if (x.Months == preg.Months && x.Weight == 1)
                    {
                        if (preg.Weight > 60)
                        {
                            <tr>
                                <td>@preg.Name</td>
                                <td>@preg.LastName</td>
                                <td>@preg.Months</td>
                                <td>@preg.Weight</td>
                            </tr>
                        }
                    }
                    else if (x.Months == preg.Months && x.Weight == 2)
                    {
                        if (preg.Weight < 60)
                        {
                            <tr>
                                <td>@preg.Name</td>
                                        <td>@preg.LastName</td>
                                        <td>@preg.Months</td>
                                        <td>@preg.Weight</td>
                            </tr>
                        }
                    }
                
                    else if (x.Months == 0 && x.Weight == 1)
                    {
                        if (preg.Weight > 60)
                        {
                            <tr>
                                <td>@preg.Name</td>
                                <td>@preg.LastName</td>
                                <td>@preg.Months</td>
                                <td>@preg.Weight</td>
                            </tr>
                        }
                    }
                    else if (x.Months == 0 && x.Weight == 2)
                    {
                        if (preg.Weight < 60)
                        {
                            <tr>
                                <td>@preg.Name</td>
                                <td>@preg.LastName</td>
                                <td>@preg.Months</td>
                                <td>@preg.Weight</td>
                            </tr>
                        }
                    }
                }   
    </table>
}
<br />
<br />
    <a asp-action="GenerateReport" asp-controller="Prenatal" class="btn btn-primary">Print Report</a>
<br />
<br />
</body>

Nompilo PHC Website/Views/Prenatal/DocDash.cshtml
@using Microsoft.AspNetCore.Identity
@{
    Layout = null;
    string special = "@gmail.com", special1 = "@outlook.com", special2 = "@mandela.ac.za", special3 = "@nompilo.co.za";
    string name = User.Identity?.Name.ToString();
    if (name.ToLowerInvariant().Contains(special))
    {
        name = name.Replace(special, " ");
    }
    else if (name.ToLowerInvariant().Contains(special1))
    {
        name = name.Replace(special1, " ");
    }
    else if (name.ToLowerInvariant().Contains(special2))
    {
        name = name.Replace(special2, " ");
    }
    else if (name.ToLowerInvariant().Contains(special3))
    {
        name = name.Replace(special3, " ");
    }
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8" />

    @* <link rel="stylesheet" href="~/css/dashboardstyle.css" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        /* import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700");*/

        * {
            margin: 0;
            padding: 0;
            outline: none;
            border: none;
            text-decoration: none;
            box-sizing: border-box;
            font-family: "Poppins", sans-serif;
        }

        /*body {
                            background: #dfe9f5;
                        }
                        */
        .container {
            display: flex;
        }

        nav {
            position: relative;
            top: 0px;
            bottom: 0;
            height: 100vh;
            left: 0;
            background-color: #029EFF;
            /* background: #fff;*/
            width: 280px;
            overflow: hidden;
            box-shadow: 0 20px 35px rgba(0, 0, 0, 0.1);
           
        }

        .logo {
            text-align: center;
            display: flex;
            margin: 10px 0 0 10px;
        }

            .logo img {
                width: 45px;
                height: 45px;
                border-radius: 50%;
            }

            .logo span {
                font-weight: bold;
                padding-left: 15px;
                font-size: 18px;
                text-transform: uppercase;
            }

        a {
            position: relative;
            color: black;
            font-size: 14px;
            display: table;
            width: 280px;
            padding: 10px;
        }

        nav .fas {
            position: relative;
            width: 70px;
            height: 40px;
            top: 14px;
            font-size: 20px;
            text-align: center;
        }

        .nav-item {
            position: relative;
            top: 12px;
            margin-left: 10px;
        }

        a:hover {
            background: #eee;
        }

        .logout {
            position: absolute;
            bottom: 0;
        }

        section {
            width: 80%;
        }

        #back {
            border: double;
            border-radius: 7px;
            font-size: 15px;
            padding: 10px;
            background-color: lightcoral;
            cursor: pointer;
        }
        #bookh1{
            text-align: center;
            vertical-align: central;
            font-weight: bold;
            font-size:50px;
        }

        #backpic {
            align-self: center;
            margin-left: 20%;
            /*margin: auto;
                            width: 50%;*/
            cursor: default;
        }

        #chrcard {
            display: inline-block;
            width: 244px; /* Adjust the width as needed */
            margin: 2px;
            border: 1px solid #ccc;
            height: 200px;
            padding: 5px;
            box-sizing: border-box;
            border-radius: 10px;
            background-color: lightblue;
            box-shadow: 10px;
        }

        #chrcardholder {
            align-self: center;
            margin-left: 20%;
            /*margin: auto;
                    width: 50%;*/
            cursor: default;
        }

        .card-title{
            text-align:center;
        }
    </style>
</head>
<body>
    <div class="container">
        <nav>
            <ul>
                <li>
                    <a href="#" class="logo">
                        <img src="~/css/person.jpg" alt="">
                        <span class="nav-item">@name</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-home"></i>
                        <span class="nav-item">Home</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Prenatal" asp-action="Pregnantpatients">
                        <i class="fas fa-baby"></i>
                        <span class="nav-item">Pregnant patients</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Prenatal" asp-action="Pregnantpatients">
                        <i class="fas fa-user-friends"></i>
                        <span class="nav-item">Patients</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="DocTests" asp-action="Test">
                        <i class="fas fa-send"></i>
                        <span class="nav-item">Send Samples</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Prenatal" asp-action="Report">
                        <i class="fas  fa-file"></i>
                        <span class="nav-item">Patient Report</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="CheckUp" asp-action="CheckUpList">
                        <i class="fas fa-stethoscope"></i> <!-- Replace with the stethoscope icon -->
                        <span class="nav-item">Check-Up</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Booking" asp-action="ViewActiveBookings">
                        <i class="fas fa-book"></i> <!-- Replace with the book icon -->
                        <span class="nav-item">View Booking</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="doctests" asp-action="DoctorTestList">
                        <i class="fas fa-flask"></i> <!-- Replace with the flask icon -->
                        <span class="nav-item">View Test</span>
                    </a>
                </li>

                <li>
                    <a asp-controller="Dashboard" asp-action="Doctor" class="logout">
                        <i class="fas fa-sign-out-alt"></i>
                        <span class="nav-item">Back</span>
                    </a>
                </li>
            </ul>
        </nav>
        <section class="main">
            <h1 id="bookh1">Prenatal Care</h1>
            <br />
            <br />
            <div id="backpic">
                <img src="~/css/docprenatal.jpg" />
            </div>
            <br />
            <br />
            <br />
            <div id="chrcardholder">
                <div class="card" id="chrcard">
                    <div class="card-body">
                        <h4 class="card-title">Goals</h4>
                        <p class="card-text">Ensure the physical, mental, and emotional well-being of pregnant individuals by providing comprehensive prenatal care.</p>
                    </div>
                </div>
                <div class="card" id="chrcard">
                    <div class="card-body">
                        <h4 class="card-title">Mission</h4>
                        <p class="card-text">To provide comprehensive, compassionate, and evidence-based prenatal care, placing the health and well-being of expectant parents and their unborn children at the forefront.</p>
                    </div>
                </div>
                <div class="card" id="chrcard">
                    <div class="card-body">
                        <h4 class="card-title">Vision</h4>
                        <p class="card-text">A future where every pregnancy is supported with exceptional prenatal care, ensuring the health, safety, and happiness of both mother and baby. </p>
                    </div>
                </div>
            </div>
        </section>
    </div>

</body>
</html>

Nompilo PHC Website/Views/Prenatal/Patients.cshtml
@model PrenatalPatients
@{
    ViewData["Title"] = "Patients";
    Layout = "~/Views/Shared/DoctorLayout.cshtml";
}
<body id="home">
<style>
    #inputes {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        cursor: pointer;
        font-size: 18px;
    }
</style>
<h1 id="bookh1">Add Prenantal Patients</h1>
<form class="card" id="hold" asp-controller="Prenatal" asp-action="AddPatients">
    <label asp-for="Name"></label>
    <select asp-for="Name" asp-items="ViewBag.PatientN" aria-required="true" id="inputes">
        <option disabled selected>---Please select a name----</option>
    </select>
    <span asp-validation-for="Name" class="text-danger"></span>
    <label asp-for="LastName"></label>
    <select asp-for="LastName" asp-items="ViewBag.PatientL" aria-required="true" id="inputes">
        <option disabled selected>---Please select a lastname----</option>
    </select>
    <span asp-validation-for="LastName" class="text-danger"></span>
    <label asp-for="Date"></label>
    <select asp-for="Date" asp-items="ViewBag.PatientD" aria-required="true" id="inputes">
        <option disabled selected>---Please select a service----</option>
    </select>
    <span asp-validation-for="Date" class="text-danger"></span>
    <label asp-for="Months"></label>
    <input asp-for="Months" type="number" />
    <span asp-validation-for="Months" class="text-danger"></span>
    <label asp-for="Weight"></label>
    <input asp-for="Weight" type="number" placeholder="Patient weight in Kg's'"/>
    <span asp-validation-for="Weight" class="text-danger"></span>
    <label asp-for="Urine"></label>
    <input asp-for="Urine" type="text" />
    <span asp-validation-for="Urine" class="text-danger"></span>
    <button class="w-100 btn btn-lg btn-primary" type="submit" id="showPopupButton">Add Patient</button>
    <br />
    <a asp-action="DisplayP" asp-controller="Prenatal" class="w-100 btn btn-lg btn-primary">Display Patient</a>

</form>
<br />
<br />
<br />
<br />
<a asp-action="DocDash" asp-controller="Prenatal"><button id="back" class="btn-danger">Back</button></a>
</body>

Nompilo PHC Website/Views/Prenatal/Update.cshtml
@{
    ViewData["Title"] = "Update";
    Layout = "DoctorLayout.cshtml";
}

<h1>Update</h1>