Nompilo PHC Website/Controllers/MethodController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nompilo_PHC_Website.Data;
using Nompilo_PHC_Website.Models;
using System.Diagnostics.Metrics;

namespace Nompilo_PHC_Website.Controllers
{
    public class MethodController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public MethodController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index(string search)
        {
            var method = _dbContext.TestMethods.Include(t => t.Tests)
                .Include(i => i.Instruments)
                .Where(s =>s.status =="Active")
                .ToList();

            if (search != "" && search != null)
            {
                method = _dbContext.TestMethods.Include(t => t.Tests)
                .Where(m => m.MethodName.Contains(search)||m.Description.Contains(search))
                .Include(i => i.Instruments)
                .Where(s => s.status == "Active")
                .ToList();
            }
            else
            {
                method = _dbContext.TestMethods.Include(t => t.Tests)
                .Include(i => i.Instruments)
                .Where(s => s.status == "Active")
                .ToList();
            }

            return View(method);
        }

        
        [HttpGet]
        public IActionResult Insert()
        {
            ViewData["testId"] = new SelectList(_dbContext.Tests, "testId", "testfor");
            ViewData["instrumentId"] = new SelectList(_dbContext.Instruments, "instrumentId", "name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(TestMethod method)
        {


            if(method.Description == null||method.MethodName == null)
            {
                ViewData["instrumentId"] = new SelectList(_dbContext.Instruments, "instrumentId", "name");
                ViewData["testId"] = new SelectList(_dbContext.Tests, "testId", "testfor");
                return View("Insert", method);
            }

            
            method.status = "Active";
            _dbContext.TestMethods.Add(method);
            _dbContext.SaveChanges();
            TempData["successAlert"] = "Record saved successfully!";
            return RedirectToAction("Index");
                       
            
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            ViewData["instrumentId"] = new SelectList(_dbContext.Instruments, "instrumentId", "name");
            ViewData["testId"] = new SelectList(_dbContext.Tests, "testId", "testfor");
            if (id == 0)
            {
                return View();
            }
            else
            {
                return View(_dbContext.TestMethods.Find(id));
            }
        }
        [HttpPost]
        public IActionResult Update(TestMethod method)
        {
            if (method.MethodName == null || method.Description == null)
            {
                ViewData["instrumentId"] = new SelectList(_dbContext.Instruments, "instrumentId", "name");
                ViewData["testId"] = new SelectList(_dbContext.Tests, "testId", "testfor");
                return View("Update", method);
            }
            
            method.status = "Active";
            _dbContext.TestMethods.Update(method);
            _dbContext.SaveChanges();
            TempData["successAlert"] = "Record updated successfully!";
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _dbContext.TestMethods == null)
            {
                return NotFound();
            }
            var method = await _dbContext.TestMethods.FirstOrDefaultAsync(x => x.methodId == id);
            if (method == null)
            {
                return NotFound();
            }
            return View(method);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_dbContext.TestMethods == null)
            {
                return Problem("Entity set 'dbContext' is null");
            }
            var method = await _dbContext.TestMethods.FindAsync(id);
            if (method != null)
            {
                method.status = "In-Active";
                _dbContext.TestMethods.Update(method);
            }
            await _dbContext.SaveChangesAsync();
            TempData["successAlert"] = "Record deleted successfully!";
            return RedirectToAction(nameof(Index));

        }

    }
}

Nompilo PHC Website/Views/Method/Delete.cshtml
@model Nompilo_PHC_Website.Models.TestMethod
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LabLayout.cshtml";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
<h1 class="bg bg-danger text-center">Delete</h1>

<h3>Are you sure you want to delete this test method?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tests.testfor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MethodName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>

    </dl>

    <form asp-action="Delete">
        <div class="form-group row">
            <div class="col-8 offset-2 row">
                <input type="hidden" asp-for="methodId" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a asp-action="Index">Back to List</a>
            </div>
        </div>

    </form>
</div>

Nompilo PHC Website/Views/Method/Index.cshtml
@model IEnumerable<Nompilo_PHC_Website.Models.TestMethod>

@{
    ViewData["Title"] = "Test Methods";
    Layout = "~/Views/Shared/_LabLayout.cshtml";
}



<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
<p>
    <h2 class="bg bg-info text-center"><i class="fa fa-table" aria-hidden="true" style="font-size:48px;color:forestgreen"></i>Test Method List</h2>
    <a asp-action="Insert" class="btn btn-sm btn-primary">Add New Method</a><br />
    <form method="post">
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <input type="text" name="search" placeholder="Enter Keyword" class="inputComn form-control" />
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <div class="searchIcon">
                        <button type="submit" class="searchBtn btn btn-success">
                            Search
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</p>
@if (TempData["successAlert"] != null)
{
    <p class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success:</strong>   @TempData["successAlert"]
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
    </p>
}


@if (!Model.Any())
{
    <div class="alert alert-info" role="alert">
        You currently do not have any test method records
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>

                <th>
                    @Html.DisplayNameFor(model => model.MethodName)
                </th>
                <th>
                    Test For
                </th>
                <th>
                    Instrument
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>


                    <td>
                        @Html.DisplayFor(modelItem => item.MethodName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tests.testfor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Instruments.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>

                    <td>

                        <a asp-action="Update" asp-route-id="@item.methodId" class="btn btn-sm btn-info"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.methodId" class="btn btn-sm btn-danger"><i class="fa fa-trash" aria-hidden="true"></i>Delete</a>
                                                
                    </td>



                </tr>
            }



        </tbody>



    </table>
}

Nompilo PHC Website/Views/Method/Insert.cshtml
@model TestMethod
@{
    ViewData["Title"] = "Test Method";
    Layout = "~/Views/Shared/_LabLayout.cshtml";
}


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
<style>
    textarea {
        width: 100%;
        height: 150px;
        padding: 12px 20px;
        box-sizing: border-box;
        border: 2px solid #ccc;
        border-radius: 4px;
        background-color: #f8f8f8;
        font-size: 16px;
        resize: none;
    }
</style>
<h2 class="bg bg-info text-center">Manage Test Methods</h2>
<div class="alert alert-info text-center" role="alert">
    Provide information for test methods used in the laboratory
</div>
<div class="container-fluid">
    <form method="post" class="form" enctype="multipart/form-data">

        <div asp-validation-summary="ModelOnly" class="text-danger" />
        <div class="row">
            <div class="col-12">
                <input type="hidden" asp-for="status" />
                <div class="form-group row form-floating">
                    <div class="col-4">
                        <label asp-for="MethodName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Tests"></label>
                    </div>

                </div>
                <div class="form-group row ">
                    <div class="col-4">
                        <input asp-for="MethodName" type="text" class="form-control" aria-required="ttrue" />
                        <span asp-validation-for="MethodName" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <select asp-for="testId" class="form-control" asp-items="ViewBag.testId">
                            <option disabled selected>--Select Test--</option>
                        </select>
                        <span asp-validation-for="testId" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row form-floating">
                    <div class="col-4">
                        <label asp-for="Instruments"></label>
                    </div>


                </div>
                <div class="form-group row form-floating">
                    <div class="col-8">
                        <select asp-for="instrumentId" class="form-control" asp-items="ViewBag.instrumentId">
                            <option disabled selected>--Select Instrument--</option>
                        </select>
                        <span asp-validation-for="instrumentId" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row form-floating">
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>


                </div>
                <div class="form-group row form-floating">
                    <div class="col-8">
                        <textarea asp-for="Description" class="form-control" aria-required="true">Enter instrument description.</textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <br /><br />
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Submit" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" asp-controller="Method" class="btn btn-secondary w-75"><i class="fa-solid fa-table"></i>Go To List</a>
                        </div>
                    </div>

                </div>

            </div>
        </div>



    </form>
</div>

Nompilo PHC Website/Views/Method/Update.cshtml
@model TestMethod
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_LabLayout.cshtml";
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
<style>
    textarea {
        width: 100%;
        height: 150px;
        padding: 12px 20px;
        box-sizing: border-box;
        border: 2px solid #ccc;
        border-radius: 4px;
        background-color: #f8f8f8;
        font-size: 16px;
        resize: none;
    }
</style>
<h2 class="bg bg-info text-center">Manage Test Instrument</h2>
<div class="alert alert-info text-center" role="alert">
    Provide information for test instruments used in the laboratory
</div>
<div class="container-fluid">
    <form method="post" class="form" enctype="multipart/form-data">

        <div asp-validation-summary="ModelOnly" class="text-danger" />
        <div class="row">
            <div class="col-12">
                <input asp-for="methodId" type="hidden" />
                <div class="form-group row form-floating">
                    <div class="col-4">
                        <label asp-for="MethodName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Tests"></label>
                    </div>

                </div>
                <div class="form-group row ">
                    <div class="col-4">
                        <input asp-for="MethodName" type="text" class="form-control" aria-required="true" />
                        <span asp-validation-for="MethodName" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <select asp-for="testId" class="form-control" asp-items="ViewBag.testId">
                            <option disabled selected>--Select Test--</option>
                        </select>
                        <span asp-validation-for="testId" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row form-floating">
                    <div class="col-4">
                        <label asp-for="Instruments"></label>
                    </div>


                </div>
                <div class="form-group row form-floating">
                    <div class="col-8">
                        <select asp-for="instrumentId" class="form-control" asp-items="ViewBag.instrumentId">
                            <option disabled selected>--Select Test--</option>
                        </select>
                        <span asp-validation-for="instrumentId" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row form-floating">
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>


                </div>
                <div class="form-group row form-floating">
                    <div class="col-8">
                        <textarea asp-for="Description" class="form-control" aria-required="true">Enter instrument description.</textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <br /><br />
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Submit" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" asp-controller="Method" class="btn btn-secondary w-75"><i class="fa-solid fa-table"></i>Go To List</a>
                        </div>
                    </div>

                </div>

            </div>
        </div>



    </form>
</div>